version: "3.7"

services:
  db_dev:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gophkeeper_dev
    expose:
      # publish port on docker network
      - "5432"
    ports:
      # exposed to host (host:container)
      - "5433:5432"