package errors

var (
	ErrLogin                       = "Неудачная попытка аутентификации"
	ErrRegistration                = "Неудачная попытка регистрации"
	ErrUserExist                   = "Пользователь с таким username зарегистрирован"
	ErrUsernameIncorrect           = "Длинна username должна быть не менее шести символов"
	ErrPasswordIncorrect           = "Пароль должен состоять минимум из 8 букв, 1 цифра, 1 верхний регистр, 1 специальный символ (пример: Password-123)"
	ErrPasswordDifferent           = "Пароли не совпали"
	ErrNameEmpty                   = "Name не заполнен"
	ErrTextEmpty                   = "Data не заполнен"
	ErrDescriptionEmpty            = "Description не заполнен"
	ErrTextExist                   = "Текст с таким name уже существует"
	ErrLoginPasswordExist          = "Логин пароль с таким name уже существует"
	ErrBinaryExist                 = "Файл с таким name уже существует"
	ErrLoginEmpty                  = "Login не заполнен"
	ErrPasswordEmpty               = "Password не заполнен"
	ErrCardExist                   = "Карта с таким name уже существует"
	ErrPaymentSystemEmpty          = "Payment System не заполнен"
	ErrNumberEmpty                 = "Number не заполнен"
	ErrNumberIncorrect             = "Number некорректный (пример: 4532015112830366)"
	ErrHolderEmpty                 = "Holder не заполнен"
	ErrEndDateEmpty                = "End Date не заполнен"
	ErrEndDateIncorrect            = "End Date некорректный (пример: 01/02/2006)"
	ErrCvcEmpty                    = "CVC не заполнен"
	ErrCvcIncorrect                = "CVC некорректный (пример: 123)"
	ErrLoginPasswordCreate         = "Ошибка при добавлении логин-пароль (попробуйте обновить данные)"
	ErrLoginPasswordUpdate         = "Ошибка при изменении логин-пароль (попробуйте обновить данные)"
	ErrTextCreate                  = "Ошибка при добавлении текста (попробуйте обновить данные)"
	ErrTextUpdate                  = "Ошибка при изменении текста (попробуйте обновить данные)"
	ErrCardCreate                  = "Ошибка при добавлении карты (попробуйте обновить данные)"
	ErrCardUpdate                  = "Ошибка при изменении карты (попробуйте обновить данные)"
	ErrLoginPasswordTblIndexDelete = "Выберите в таблице логин-пароль, который хотите удалить"
	ErrLoginPasswordTblIndexUpdate = "Выберите в таблице логин-пароль, который хотите изменить"
	ErrTextTblIndexDelete          = "Выберите в таблице текст, который хотите удалить"
	ErrTextTblIndexUpdate          = "Выберите в таблице текст, который хотите изменить"
	ErrCardTblIndexDelete          = "Выберите в таблице карту, которую хотите удалить"
	ErrCardTblIndexUpdate          = "Выберите в таблице карту, которую хотите изменить"
	ErrUpload                      = "Ошибка при загрузке файла (попробуйте обновить данные)"
	ErrBinaryTblIndexDownload      = "Выберите в таблице файл, который хотите скачать"
	ErrBinaryTblIndexDelete        = "Выберите в таблице файл, который хотите удалить"
)
